services:
  - type: web
    name: chaos-game-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: FRONTEND_URL
        value: https://graficas-web-blush.vercel.app